const hexagrams = [
   {
      "number":1,
      "names":[
         "Heaven",
         "Sun Rising"
      ],
      "chinese":"乾",
      "pinyin":"qián",
      "character":"䷀",
      "value":0b111111
   },
   {
      "number":2,
      "names":[
         "Earth",
         "Earth Flow"
      ],
      "chinese":"坤",
      "pinyin":"kūn",
      "character":"䷁",
      "value":0b000000
   },
   {
      "number":3,
      "names":[
         "Difficult Birth",
         "Sprout"
      ],
      "chinese":"屯",
      "pinyin":"zhūn",
      "character":"䷂",
      "value":0b010001
   },
   {
      "number":4,
      "names":[
         "Youthful Folly",
         "Dodder"
      ],
      "chinese":"蒙",
      "pinyin":"méng",
      "character":"䷃",
      "value":0b100010
   },
   {
      "number":5,
      "names":[
         "Waiting",
         "Cloudburst"
      ],
      "chinese":"需",
      "pinyin":"xū",
      "character":"䷄",
      "value":0b010111
   },
   {
      "number":6,
      "names":[
         "Conflict",
         "Dispute"
      ],
      "chinese":"訟",
      "pinyin":"sòng",
      "character":"䷅",
      "value":0b111010
   },
   {
      "number":7,
      "names":[
         "The Army"
      ],
      "chinese":"師",
      "pinyin":"shī",
      "character":"䷆",
      "value":0b000010
   },
   {
      "number":8,
      "names":[
         "Closeness",
         "Side by Side"
      ],
      "chinese":"比",
      "pinyin":"bǐ",
      "character":"䷇",
      "value":0b010000
   },
   {
      "number":9,
      "names":[
         "Slight Restraint",
         "Lesser Husbandry"
      ],
      "chinese":"小畜",
      "pinyin":"xiǎo chù",
      "character":"䷈",
      "value":0b110111
   },
   {
      "number":10,
      "names":[
         "Stepping",
         "Step"
      ],
      "chinese":"履",
      "pinyin":"lǚ",
      "character":"䷉",
      "value":0b111011
   },
   {
      "number":11,
      "names":[
         "Grandeur",
         "Grand"
      ],
      "chinese":"泰",
      "pinyin":"tài",
      "character":"䷊",
      "value":0b000111
   },
   {
      "number":12,
      "names":[
         "Obstruction",
         "Wife"
      ],
      "chinese":"否",
      "pinyin":"pǐ",
      "character":"䷋",
      "value":0b111000
   },
   {
      "number":13,
      "names":[
         "Fellowship",
         "Assembly"
      ],
      "chinese":"同人",
      "pinyin":"tóng rén",
      "character":"䷌",
      "value":0b111101
   },
   {
      "number":14,
      "names":[
         "Great Measure"
      ],
      "chinese":"大有",
      "pinyin":"dà yǒu",
      "character":"䷍",
      "value":0b101111
   },
   {
      "number":15,
      "names":[
         "Humility",
         "Rats"
      ],
      "chinese":"謙",
      "pinyin":"qiān",
      "character":"䷎",
      "value":0b000100
   },
   {
      "number":16,
      "names":[
         "Elation",
         "Elephants"
      ],
      "chinese":"豫",
      "pinyin":"yù",
      "character":"䷏",
      "value":0b001000
   },
   {
      "number":17,
      "names":[
         "Following",
         "Pursuit"
      ],
      "chinese":"隨",
      "pinyin":"suí",
      "character":"䷐",
      "value":0b011001
   },
   {
      "number":18,
      "names":[
         "Blight"
      ],
      "chinese":"蠱",
      "pinyin":"gǔ",
      "character":"䷑",
      "value":0b100110
   },
   {
      "number":19,
      "names":[
         "Approach",
         "Wailing"
      ],
      "chinese":"臨",
      "pinyin":"lín",
      "character":"䷒",
      "value":0b000011
   },
   {
      "number":20,
      "names":[
         "Observation",
         "Observing"
      ],
      "chinese":"觀",
      "pinyin":"guān",
      "character":"䷓",
      "value":0b110000
   },
   {
      "number":21,
      "names":[
         "Biting"
      ],
      "chinese":"噬嗑",
      "pinyin":"shì kè",
      "character":"䷔",
      "value":0b101001
   },
   {
      "number":22,
      "names":[
         "Adornment",
         "Fine"
      ],
      "chinese":"賁",
      "pinyin":"bì",
      "character":"䷕",
      "value":0b100101
   },
   {
      "number":23,
      "names":[
         "Pulling Apart",
         "Stripped"
      ],
      "chinese":"剝",
      "pinyin":"bō",
      "character":"䷖",
      "value":0b100000
   },
   {
      "number":24,
      "names":[
         "Return"
      ],
      "chinese":"復",
      "pinyin":"fù",
      "character":"䷗",
      "value":0b000001
   },
   {
      "number":25,
      "names":[
         "Freedom from Guile",
         "Possession"
      ],
      "chinese":"無妄",
      "pinyin":"wú wàng",
      "character":"䷘",
      "value":0b111001
   },
   {
      "number":26,
      "names":[
         "Great Restraint",
         "Greater Husbandry"
      ],
      "chinese":"大畜",
      "pinyin":"dà chù",
      "character":"䷙",
      "value":0b100111
   },
   {
      "number":27,
      "names":[
         "Nourishment",
         "Breasts"
      ],
      "chinese":"頤",
      "pinyin":"yí",
      "character":"䷚",
      "value":0b100001
   },
   {
      "number":28,
      "names":[
         "Great Excess"
      ],
      "chinese":"大過",
      "pinyin":"dà guò",
      "character":"䷛",
      "value":0b011110
   },
   {
      "number":29,
      "names":[
         "The Abyss",
         "Pit"
      ],
      "chinese":"坎",
      "pinyin":"kǎn",
      "character":"䷜",
      "value":0b010010
   },
   {
      "number":30,
      "names":[
         "Fire",
         "Net, Oriole"
      ],
      "chinese":"離",
      "pinyin":"lí",
      "character":"䷝",
      "value":0b101101
   },
   {
      "number":31,
      "names":[
         "Resonance",
         "Tingling"
      ],
      "chinese":"咸",
      "pinyin":"xián",
      "character":"䷞",
      "value":0b011100
   },
   {
      "number":32,
      "names":[
         "Endurance",
         "Fixing"
      ],
      "chinese":"恆",
      "pinyin":"héng",
      "character":"䷟",
      "value":0b001110
   },
   {
      "number":33,
      "names":[
         "Retreat",
         "Piglet"
      ],
      "chinese":"遯",
      "pinyin":"dùn",
      "character":"䷠",
      "value":0b111100
   },
   {
      "number":34,
      "names":[
         "Great Might",
         "Wound"
      ],
      "chinese":"大壯",
      "pinyin":"dà zhuàng",
      "character":"䷡",
      "value":0b001111
   },
   {
      "number":35,
      "names":[
         "Advance",
         "Forward"
      ],
      "chinese":"晉",
      "pinyin":"jìn",
      "character":"䷢",
      "value":0b101000
   },
   {
      "number":36,
      "names":[
         "Darkness",
         "Pelican Calling"
      ],
      "chinese":"明夷",
      "pinyin":"míng yí",
      "character":"䷣",
      "value":0b000101
   },
   {
      "number":37,
      "names":[
         "The Family"
      ],
      "chinese":"家人",
      "pinyin":"jiā rén",
      "character":"䷤",
      "value":0b110101
   },
   {
      "number":38,
      "names":[
         "Opposition",
         "Watching"
      ],
      "chinese":"睽",
      "pinyin":"kuí",
      "character":"䷥",
      "value":0b101011
   },
   {
      "number":39,
      "names":[
         "Adversity",
         "Stumbling"
      ],
      "chinese":"蹇",
      "pinyin":"jiǎn",
      "character":"䷦",
      "value":0b010100
   },
   {
      "number":40,
      "names":[
         "Release"
      ],
      "chinese":"解",
      "pinyin":"xiè",
      "character":"䷧",
      "value":0b001010
   },
   {
      "number":41,
      "names":[
         "Decrease"
      ],
      "chinese":"損",
      "pinyin":"sǔn",
      "character":"䷨",
      "value":0b100011
   },
   {
      "number":42,
      "names":[
         "Increase"
      ],
      "chinese":"益",
      "pinyin":"yì",
      "character":"䷩",
      "value":0b110001
   },
   {
      "number":43,
      "names":[
         "Resolution",
         "Tripping"
      ],
      "chinese":"夬",
      "pinyin":"guài",
      "character":"䷪",
      "value":0b011111
   },
   {
      "number":44,
      "names":[
         "Encounter"
      ],
      "chinese":"姤",
      "pinyin":"gòu",
      "character":"䷫",
      "value":0b111110
   },
   {
      "number":45,
      "names":[
         "Gathering",
         "Deranged"
      ],
      "chinese":"萃",
      "pinyin":"cuì",
      "character":"䷬",
      "value":0b011000
   },
   {
      "number":46,
      "names":[
         "Ascent"
      ],
      "chinese":"升",
      "pinyin":"shēng",
      "character":"䷭",
      "value":0b000110
   },
   {
      "number":47,
      "names":[
         "Confinement",
         "Pressed"
      ],
      "chinese":"困",
      "pinyin":"kùn",
      "character":"䷮",
      "value":0b011010
   },
   {
      "number":48,
      "names":[
         "The Well"
      ],
      "chinese":"井",
      "pinyin":"jǐng",
      "character":"䷯",
      "value":0b010110
   },
   {
      "number":49,
      "names":[
         "Change",
         "Hide"
      ],
      "chinese":"革",
      "pinyin":"gé",
      "character":"䷰",
      "value":0b011101
   },
   {
      "number":50,
      "names":[
         "The Cauldron"
      ],
      "chinese":"鼎",
      "pinyin":"dǐng",
      "character":"䷱",
      "value":0b101110
   },
   {
      "number":51,
      "names":[
         "Quake"
      ],
      "chinese":"震",
      "pinyin":"zhèn",
      "character":"䷲",
      "value":0b001001
   },
   {
      "number":52,
      "names":[
         "Mountain",
         "Tending"
      ],
      "chinese":"艮",
      "pinyin":"gèn",
      "character":"䷳",
      "value":0b100100
   },
   {
      "number":53,
      "names":[
         "Gradual",
         "Alighting"
      ],
      "chinese":"漸",
      "pinyin":"jiàn",
      "character":"䷴",
      "value":0b110100
   },
   {
      "number":54,
      "names":[
         "The Marrying Maiden"
      ],
      "chinese":"歸妹",
      "pinyin":"guī mèi",
      "character":"䷵",
      "value":0b001011
   },
   {
      "number":55,
      "names":[
         "Canopy",
         "Citadel"
      ],
      "chinese":"豐",
      "pinyin":"fēng",
      "character":"䷶",
      "value":0b001101
   },
   {
      "number":56,
      "names":[
         "The Wanderer",
         "Sojourner"
      ],
      "chinese":"旅",
      "pinyin":"lǚ",
      "character":"䷷",
      "value":0b101100
   },
   {
      "number":57,
      "names":[
         "Kneeling",
         "Offering"
      ],
      "chinese":"巽",
      "pinyin":"xùn",
      "character":"䷸",
      "value":0b110110
   },
   {
      "number":58,
      "names":[
         "Joy"
      ],
      "chinese":"兌",
      "pinyin":"duì",
      "character":"䷹",
      "value":0b011011
   },
   {
      "number":59,
      "names":[
         "Dispersal",
         "Spurting"
      ],
      "chinese":"渙",
      "pinyin":"huàn",
      "character":"䷺",
      "value":0b110010
   },
   {
      "number":60,
      "names":[
         "Notch"
      ],
      "chinese":"節",
      "pinyin":"jié",
      "character":"䷻",
      "value":0b010011
   },
   {
      "number":61,
      "names":[
         "Good Faith",
         "Captives Taken"
      ],
      "chinese":"中孚",
      "pinyin":"zhōng fú",
      "character":"䷼",
      "value":0b110011
   },
   {
      "number":62,
      "names":[
         "Slight Excess"
      ],
      "chinese":"小過",
      "pinyin":"xiǎo guò",
      "character":"䷽",
      "value":0b001100
   },
   {
      "number":63,
      "names":[
         "Complete",
         "Completion"
      ],
      "chinese":"既濟",
      "pinyin":"jì jì",
      "character":"䷾",
      "value":0b010101
   },
   {
      "number":64,
      "names":[
         "Incomplete"
      ],
      "chinese":"未濟",
      "pinyin":"wèi jì",
      "character":"䷿",
      "value":0b101010
   }
];
